### PR TITLE
CPI Config Support

### PR DESCRIPTION
**Pull request by evandbrown**
[WIP] support CPI config

### CODE REVIEW

**Comment by evandbrown** [comment]
Addressing #270

**Comment by evandbrown** [comment]
@cppforlife I've made a few changes, mostly to improve testability, and have a few general questions:
- Do we need to support an `info` method?
- Is it correct that when this change is released, the Google CPI will require BOSH 261+?
- Does BATS provide sufficient coverage for testing this feature?

**Comment by evandbrown** [comment]
Integration and unit tests are passing locally. I'm going to merge this to `develop` and open a separate PR to discuss before merging to `master`.

**Comment by cppforlife** [comment]
> Do we need to support an info method?

info's stemcell-formats tell director which stemcells to try to upload to the cpi: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/src/bosh-google-cpi/action/info.go. also with upcoming changes it would indicate which max cpi contract cpi supports.

> Is it correct that when this change is released, the Google CPI will require BOSH 261+?

this is all additive, unless you start requiring some configuration to be passed in context vs just merging it on top of job level config.

> Does BATS provide sufficient coverage for testing this feature?

bats does not test this feature at all. may be something to add in future.

**Pull request merged**
