### PR TITLE
Disable HTTP/2 on GoogleClient

### PR DESCRIPTION
**Pull request by zaksoup**
We believe this solves an issue we've seen regularly in our CI over the past month: 

```
Deploying:
  Deleting existing instance 'unknown/0':
    Checking existence of vm for instance 'unknown/0':
      Checking existence of VM 'vm-117d6b0e-b856-4a21-5aad-b9c2523ae2f7':
        CPI 'has_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Finding vm 'vm-117d6b0e-b856-4a21-5aad-b9c2523ae2f7': Failed to find Google Instance 'vm-117d6b0e-b856-4a21-5aad-b9c2523ae2f7': Get https://www.googleapis.com/compute/v1/projects/cf-bosh-concourse/aggregated/instances?alt=json\u0026filter=name+eq+.%!A(MISSING)vm-117d6b0e-b856-4a21-5aad-b9c2523ae2f7: stream error: stream ID 1; PROTOCOL_ERROR","ok_to_retry":false}
```

We've seen a number of issues opened against go that indicate to us that HTTP2 is not reasonably stable:
https://github.com/golang/go/issues/16847
https://github.com/golang/go/issues/16412
https://github.com/golang/go/issues/15425

This being the case we propose disabling HTTP2 on the client until we upgrade to go 1.8 or feel that HTTP2 client in go is stable enough for prod.

We haven't been able to empirically test this — the problem has been quite elusive: appearing in some accounts but not others, disappearing & re-appearing a week later, etc...

### CODE REVIEW

**Comment by johnsonj** [comment]
Thanks @zaksoup -

Is there added complexity in upgrading to the latest golang instead? The Go team has been investing a lot in fixing http/2 issues, "If you found a case where h2 doesn't work, the correct course of action is to file a bug about fixing h2 with the repro steps you found, NOT to file bugs about making it easier to document how to disable it." - @bradfitz

I personally dev the CPI on some flavor 1.8 so I don't see an issue with upgrading our package unless there's some stemcell/director thing I don't know about.

**Comment by bradfitz** [comment]
I don't think disabling HTTP/2 for unknown reasons is a great idea. I'd definitely understand the problem before disabling anything. But once it's understood, if it's actually a bug in our HTTP/2 client, we will fix it immediately.

**Comment by zaksoup** [comment]
> @johnsonj: I personally dev the CPI on some flavor 1.8 so I don't see an issue with upgrading our package unless there's some stemcell/director thing I don't know about.

@cppforlife was concerned as other teams (Diego) saw performance regressions there that might affect us. From the @ematpl:

> Specifically, the auctioneer (the dæmon) observed simultaneous request to get state suddenly receive client-side timeouts from the cell API. There was high variance. The server was responding to `ginkgo --race`. We use the cgo libraries.

If @cppforlife is okay with 1.8 we're happy to upgrade and close this issue.

---

> @bradfitz: I don't think disabling HTTP/2 for unknown reasons is a great idea.

We agree, though we hesitate to term them "unknown reasons". In this case we struggled to find a consistent manner to reproduce the problem: Sometimes the connections to the Google Cloud API endpoints would fail with symptoms identical to those described in the linked HTTP/2 issues, sometimes it would succeed. Is there a staggered HTTP/2 rollout on Google Cloud API? Maybe that would account for the difficulty we've had reproducing the problem.

We gathered the following empirical information leading up to disabling HTTP/2 as an alternative to 1.8 by running `bosh create-env`/`bosh delete-env` in a loop.:

* Out of **16** 1.7.1 deploy/delete cycles we had 4 distinct failures. This is a failure rate of **25%**

* On the 1.8.1 side we ran **20** 1.8.1 deploy/delete cycles with 0 failures which gives us a **99.6%** confidence that upgrading to Golang 1.8.1 will fix the problem.

* On the 1.7.1+disabled HTTP/2 we also didn't see any failures after over a hundred runs, but that particular Google Project seemed to become "immune" to the problem, and we weren't able to reproduce it again.

---

**Recap**: We agree, disabling HTTP/2 without a clear and obvious reason does not make us happy. That being said we've struggled to truly understand this issue and the experiments and disabling HTTP/2 seemed to be a solution that allowed us to stay on go 1.7.1. I'd be happy to reopen the discussion of upgrading go with @cppforlife.

**Comment by ematpl** [comment]
@zaksoup: @jvshahid and @nkaviani have been looking into our problems with the Diego auctioneer, and they seem primarily related to a change in the HTTP chunked reader between golang 1.7 and 1.8 (from https://github.com/golang/go/issues/17355) that causes the client not to get an EOF on reading the end of the request body, and then the connection does not get reused on subsequent requests. More details here, with the caveat that our investigation is still in flight: https://www.pivotaltracker.com/story/show/144907419/comments/171947003

**Comment by johnsonj** [comment]
Awesome metrics :100:

If there's no objection let's upgrade the CPI and the send bugs to @bradfitz and the gang if we need to roll back. They're extremely fast to fix issues and all will benefit from keeping the edge working great.

@ematpl sounds like is a separate issue (that I'm very curious to see how it goes). The CPI doesn't have the same performance/load/concurrency expectations as the auctioneer so I don't think we'll run into the same problem.

**Comment by zaksoup** [comment]
@johnsonj Hey, we've had a conversation with @cppforlife and it looks like upgrading to go 1.8 is the way forward here. We don't have access to the `private.yml` for this bosh release so can you do that yourself. We'll ping you offline about possibly sharing that private.yml if we're going to continue to contribute PRs to this repo that may touch release properties :)

**Pull request closed without merging**
