### PR TITLE
Remove light-stemcell pipeline from bosh-google-cpi-release

### PR DESCRIPTION
**Pull request by cdutra**
- moved to cloudfoundry/bosh-google-light-stemcell-builder

[#152327898](https://www.pivotaltracker.com/story/show/152327898)

### CODE REVIEW

**Comment by johnsonj** [comment]
thanks @cdutra !

**Comment by johnsonj** [comment]
@cdutra What's the status on the heavy stemcells? Will those eventually move out of the CPI project as well?

**Comment by dpb587-pivotal** [comment]
Hmm, I don't think the heavy pipelines here are actually being used. I think they were used when the CPI was originally under development. Core team publishes the Google stemcells now alongside the other IaaS stemcells.

**Comment by cdutra** [comment]
Exactly what Danny said. Sorry for not responding earlier. It can be removed too

Chris Dutra

**Comment by johnsonj** [comment]
thank you!

**Pull request merged**
