### PR TITLE
Concourse documentation updates

### PR DESCRIPTION
**Pull request by cjcjameson**
We are walking through docs/concourse/README.md today, and happy to contribute back minor fixes we see. But overall, seems awesome!

### CODE REVIEW

**Comment by cjcjameson** [comment]
I'm looking for some help / advice here: (maybe from @evandbrown ?)

The terraform + manifest lead to the BOSH director having a public IP address for this Concourse walk-through. It looks like in the BOSH-only walkthrough, there's a resource with the `no-ip` tag. Is that the way you would indicate to GCP that you don't want a public IP address given to the BOSH director?

See https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/commit/48086e2cacfb2b5ceb0295bf0168747c8dfabdef where no-ip was introduced

**Comment by johnsonj** [comment]
The BOSH director in the Concourse example gets an external IP because of the `ephemeral_external_ip` cloud property on the `private` network. Setting this to false will remove the public IP from the director. It will also remove public internet access.

The `no-ip` tag is convention in the Cloud Foundry deployment. It's done so traffic can be routed to a VM that does NAT. The rule that does that is [here](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/docs/bosh/main.tf#L40)

**Comment by cjcjameson** [comment]
@johnsonj Thanks for explaining! This makes sense. My PR is unchanged.

**Comment by evandbrown** [comment]
Sorry for being super late on this! I changed the base to `develop` and merging now. Thank you for the contribution, @cjcjameson!

**Pull request merged**
